apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-petclinic
  name: spring-petclinic
  namespace: app-team-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-petclinic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-petclinic
        app.kubernetes.io/part-of: spring-petclinic
    spec:
      containers:
      - image: harbor-repo.vmware.com/dockerhub-proxy-cache/springcommunity/spring-framework-petclinic:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 15
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: spring-petclinic
  name: spring-petclinic
  namespace: app-team-1
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-petclinic